version: '3.2'

networks:
  matecat-network:
    driver: bridge

services:

  base:
    image: ostico/matecat-focal-base-image
    build: ./FocalBaseImage

  filters:
    build: ./MateCatFilters/
    container_name: docker_focal_matecat_filter
    ports:
      - "8732:8732"
    networks:
       - matecat-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
       - matecat-network

  amq:
    build: ./AMQ/
    container_name: docker_focal_amq
    ports:
      - "61613:61613"
      - "61616:61616"
      - "8161:8161"
    networks:
      matecat-network:
        aliases:
          - amq

  mysql-master:
    build:
      context: ./MySQL/
      args:
        _type_: "master"
    container_name: docker_focal_mysql_master
    ports:
     - "3307:3306"
    volumes:
      - /home/hashashiyyin/PhpstormProjects/temporary_docker_mount_volume:/mnt/external_volume:rw
    networks:
      matecat-network:
        aliases:
          - mysql-master

  mysql-slave:
    build:
      context: ./MySQL/
      args:
        _type_: "slave"
    container_name: docker_focal_mysql_slave
    ports:
     - "3308:3306"
    volumes:
      - /home/hashashiyyin/PhpstormProjects/temporary_docker_mount_volume:/mnt/external_volume:rw
    depends_on:
      - mysql-master
    networks:
      matecat-network:
        aliases:
          - mysql-slave

  proxysql:
    build: ./ProxySQL/
    container_name: docker_focal_proxysql
    ports:
      - "3306:3306"
    links:
      - mysql-master
      - mysql-slave
    volumes:
      - /home/hashashiyyin/PhpstormProjects/temporary_docker_mount_volume:/mnt/external_volume:rw
    networks:
       - matecat-network
    depends_on:
      - mysql-master
      - mysql-slave

  matecat:
    build: ./MateCatApache/
    container_name: docker_focal_matecat
    ## Remove this environment block if you don't need it ##
    environment:
      XDEBUG_CONFIG: 172.17.0.1
      FILTERS_ADDRESS: http://filters:8732/
#      SMTP_HOST: localhost
#      SMTP_PORT: 2637
    ## Remove this environment block if you don't need it ##

    volumes:
      - /home/hashashiyyin/PhpstormProjects/matecat/certs/letsencrypt:/etc/letsencrypt:rw
      - /home/hashashiyyin/PhpstormProjects/matecat:/var/www/matecat:rw
    ports:
      - "80:80"
      - "443:443"
      - "7788:7788"
    networks:
       - matecat-network
    links:
      - proxysql
      - mysql-master
      - mysql-slave
      - redis
      - amq
      - filters
    depends_on:
      - proxysql
      - mysql-master
      - mysql-slave
      - redis
      - amq
      - filters
