networks:
  matecat-network:
    driver: bridge

services:

  base:
    image: ostico/matecat-focal-base-image
    build: ./FocalBaseImage

  filters:
    build: ./MateCatFilters/
    container_name: matecat-filter
    ports:
      - "8732:8732"
    networks:
       - matecat-network

  redis:
    image: redis
    container_name: matecat-redis
    ports:
      - "6379:6379"
    networks:
       - matecat-network

  amq:
    build: ./AMQ/
    container_name: matecat-amq
    ports:
      - "61613:61613"
      - "61616:61616"
      - "8161:8161"
    networks:
      matecat-network:
        aliases:
          - amq

  mysql-master:
    build:
      context: ./MySQL/
      args:
        _type_: "master"
    container_name: matecat-mysql-master
    ports:
     - "3307:3306"
    networks:
      matecat-network:
        aliases:
          - mysql-master

  mysql-slave:
    build:
      context: ./MySQL/
      args:
        _type_: "slave"
    container_name: matecat-mysql-slave
    ports:
     - "3308:3306"
    depends_on:
      - mysql-master
    networks:
      matecat-network:
        aliases:
          - mysql-slave

  proxysql:
    build: ./ProxySQL/
    container_name: matecat-proxysql
    ports:
      - "3306:3306"
    links:
      - mysql-master
      - mysql-slave
    networks:
       - matecat-network
    depends_on:
      - mysql-master
      - mysql-slave

  matecat:
    build: ./MateCatApache/
    container_name: matecat
    ## Remove this environment block if you don't need it ##
    environment:
      XDEBUG_CONFIG: 172.19.0.1
      FILTERS_ADDRESS: http://filters:8732/
      PHP_IDE_CONFIG: serverName=dev.matecat.com
#      SMTP_HOST: localhost
#      SMTP_PORT: 2637
    ## Remove this environment block if you don't need it ##

    ports:
      - "80:80"
      - "443:443"
      - "7788:7788"
    networks:
       - matecat-network
    links:
      - proxysql
      - mysql-master
      - mysql-slave
      - redis
      - amq
      - filters
    depends_on:
      - proxysql
      - mysql-master
      - mysql-slave
      - redis
      - amq
      - filters
